version: '3'
services:
  meshly-core:
    image: andreasmolnardev/meshly-core
    ports:
      - "3003:3000"
    restart: always
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/meshly-core
      - FILEBACKEND_ENABLED=true
      - FILEBACKEND_URL=http://minio:9000
      - FILEBACKEND_ACCESS_KEY=meshlycore
      - FILEBACKEND_SECRET_KEY=meshlycore-miniofilebackend
      - FILEBACKEND_BUCKET=meshly-core-uploads

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
    volumes:
      - ../meetables_data/mongo:/data/db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=meshlycore
      - MINIO_ROOT_PASSWORD=meshlycore-miniofilebackend
    command: server /data --console-address ":9001"
    volumes:
      - ../meetables_data/minio:/data
