version: '3'
services:
  meshly-core:
    build: .
    container_name: meshly-core
    ports:
      - "3003:3000"
    restart: always
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/meshly-core

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
