services:
  meshly-core:
    build: .
    container_name: meshly-core
    ports:
      - "3000:3000"
    restart: always
    command: npm run dev
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/meshly-core
      - NODE_ENV=development
      - PORT=3000
      - FILEBACKEND_ENABLED=true
      - FILEBACKEND_URL=http://minio:9000
      - FILEBACKEND_ACCESS_KEY=meshlycore
      - FILEBACKEND_SECRET_KEY=meshlycore-miniofilebackend
      - FILEBACKEND_BUCKET=meshly-core-uploads

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: meetables
      MONGO_INITDB_ROOT_PASSWORD: meetables
    command: ["--auth"]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=meshlycore
      - MINIO_ROOT_PASSWORD=meshlycore-miniofilebackend
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  mongo-data:
  minio-data:
