const dotenv = require('dotenv')

dotenv.config();

const ENV_VARS = {
    DATABASE_URL: process.env.DATABASE_URL,
    PORT: process.env.PORT || 3000,
    JWT_SECRET: process.env.JWT_SECRET,
    NODE_ENV: process.env.NODE_ENV,
    TAG_CATEGORIES: process.env.TAG_CATEGORIES,
    DEFAULT_TAGS: JSON.parse(process.env.DEFAULT_TAGS),
    ENABLE_PROFILE_SUGGESTIONS: process.env.ENABLE_PROFILE_SUGGESTIONS,
    REQUIRED_MATCHING_TAG_CATEGORY: process.env.REQUIRED_MATCHING_TAG_CATEGORY || false,
    PROFILE_SUGGESTION_ALGORITHM_INTERVAL: process.env.PROFILE_SUGGESTION_ALGORITHM_INTERVAL || false,
    PROFILE_SUGGESTION_NEW_THRESHOLD_HOURS: parseFloat(process.env.PROFILE_SUGGESTION_NEW_THRESHOLD_HOURS) || 24,
    PROFILE_SUGGESTION_HOT_THRESHOLD: parseFloat(process.env.PROFILE_SUGGESTION_HOT_THRESHOLD) || 0.45
}

if (process.env.NODE_ENV = 'development') {
    ENV_VARS.DEV_TESTUSER_EMAIL = process.env.DEV_TESTUSER_EMAIL;
    ENV_VARS.DEV_TESTUSER_USERNAME = process.env.DEV_TESTUSER_USERNAME;
    ENV_VARS.DEV_TESTUSER_PASSWORD = process.env.DEV_TESTUSER_PASSWORD;
}

module.exports = {ENV_VARS}