const dotenv = require('dotenv')

const tags = require('./tags.json')
const config = require('./config.json')
const user_roles = require('./roles.json')
const internal_secuurity = require("./internal-security.json")
const mailing = require('./mailing.json')

dotenv.config();

const ENV_VARS = {
    DATABASE_URL: process.env.DATABASE_URL,
    PORT: process.env.PORT || 3000,
    JWT_SECRET: config.JWT_SECRET,
    NODE_ENV: config.NODE_ENV,
    TAG_CATEGORIES: config.TAG_CATEGORIES,
    USER_ROLES: user_roles,
    FILEBACKEND_ENABLED: process.env.FILEBACKEND_ENABLED || false,
    FILEBACKEND_URL: process.env.FILEBACKEND_URL,
    FILEBACKEND_ACCESS_KEY: process.env.FILEBACKEND_ACCESS_KEY,
    FILEBACKEND_SECRET_KEY: process.env.FILEBACKEND_SECRET_KEY,
    FILEBACKEND_BUCKET: process.env.FILEBACKEND_BUCKET || "meshlycore-files",
    USER_CONFIRMATION_EXPIRATION_MS: config.USER_CONFIRMATION_EXPIRATION_MS,
    DEFAULT_TAGS: tags,
    ENABLE_PROFILE_SUGGESTIONS: config.ENABLE_PROFILE_SUGGESTIONS,
    REQUIRED_MATCHING_TAG_CATEGORY: config.REQUIRED_MATCHING_TAG_CATEGORY || false,
    PROFILE_SUGGESTION_ALGORITHM_INTERVAL: config.PROFILE_SUGGESTION_ALGORITHM_INTERVAL || false,
    PROFILE_SUGGESTION_NEW_THRESHOLD_HOURS: parseFloat(config.PROFILE_SUGGESTION_NEW_THRESHOLD_HOURS) || 24,
    PROFILE_SUGGESTION_HOT_THRESHOLD: parseFloat(config.PROFILE_SUGGESTION_HOT_THRESHOLD) || 0.45,
    DEV_ADMINUSER_EMAIL: config.DEV_ADMINUSER_EMAIL,
    DEV_ADMINUSER_USERNAME: config.DEV_ADMINUSER_USERNAME,
    EXTENSIONS_EXTRA_NOTIFICATIONTYPES: config.EXTENSIONS_EXTRA_NOTIFICATIONTYPES || [],
    DISALLOWED_USER_CHANGES: internal_secuurity.USER_CHANGES.DISALLOWED_FIELDS,
    DOMAIN: config.DOMAIN,
    CONFIRMATION_MAILING: mailing.CONFIRMATION
}

if (process.env.NODE_ENV = 'development') {
    ENV_VARS.DEV_TESTUSER_EMAIL = config.DEV_TESTUSER_EMAIL;
    ENV_VARS.DEV_TESTUSER_USERNAME = config.DEV_TESTUSER_USERNAME;
    ENV_VARS.DEV_TESTUSER_PASSWORD = config.DEV_TESTUSER_PASSWORD;
}

module.exports = {ENV_VARS}