name: Deploy Main API

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: SSH then clone repo
        run: |
          ssh -o StrictHostKeyChecking=no meetables.meshlycore.test@codeclub.check24.fun << 'EOF'
            
            TEMP_DIR=$(mktemp -d)

             for PORT in 27017 3003; do
              CONTAINER_ID=\$(docker ps --filter "publish=\$PORT" --format "{{.ID}}")
              if [ ! -z "\$CONTAINER_ID" ]; then
                echo "Stopping container using port \$PORT: \$CONTAINER_ID"
                docker stop \$CONTAINER_ID
                docker rm \$CONTAINER_ID
              fi
            done
            
            git clone https://github.com/Meetables/meshly-core.git $TEMP_DIR
            
            cd $TEMP_DIR

            docker compose -f ./docker-compose.yaml down --remove-orphans
            docker network prune -f
            docker compose -f ./docker-compose.yaml up -d --force-recreate

            rm -rf $TEMP_DIR
          EOF
